### ISSUE TITLE
[Feat]:Add Styling to website

### ISSUE THREAD

**Issue by bhaavvya** [KendallDoesCoding/youtubers-birthdays#79] opened 2023-09-03 15:46 UTC
**Description:**
Enhancement
Add styling to the website to make it look attractive.

**Describe briefly how you would implement this enhancement.**
Some steps to implement this enhancement-
1. Recreate search section and add styling like add hover effects,etc.
2. Add background images to the website.
3. Style the table.

**Comment by ayushichoudhary-19** [comment] 2023-09-07 04:38
I've Submitted a PR. Please review it.

**Comment by KendallDoesCoding** [comment] 2023-09-07 07:03
> I've Submitted a PR. Please review it.

Even @bhaavvya has created a PR. We will remove both.

Next time, once the issue is made, please ask to be assigned and only once you are assigned start working on the issue, no issues this time. Thanks!

**Comment by ayushichoudhary-19** [comment] 2023-09-22 11:36
Please review my PR #83.

**Comment by KendallDoesCoding** [comment] 2023-09-23 07:03
fixed in #83

**Closed by KendallDoesCoding** 2023-09-23 07:03 UTC
